// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import HelloController from "./hello_controller"
application.register("hello", HelloController)
import ButtonPreviewController from "./button_preview_controller"
application.register("button-preview", ButtonPreviewController)
import AlertPreviewController from "./alert_preview_controller"
application.register("alert-preview", AlertPreviewController)
import DialogPreviewController from "./dialog_preview_controller"
application.register("dialog-preview", DialogPreviewController)
